Potentially Increased performance(http2.0)&Fixed parsing bug
holzmaster/OpenPr0gramm pull request #20
Opened 2019-04-08 07:54 UTC by J-kit

Fixed login bug

2019-04-09 08:05 UTC, holzmaster requested changes

2019-04-09 08:05 UTC, holzmaster commented on OpenPr0gramm.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "OpenPr0gramm.Tests", "src\OpenPr0gramm.Tests\OpenPr0gramm.Tests.csproj", "{DD756BA6-655B-4106-955F-40079EC089D3}"
Warum hat sich diese UUID geändert?

2019-04-09 08:05 UTC, holzmaster commented on OpenPr0gramm.sln
> -		{2253CE81-8EFC-485F-90BA-471EA93E2527}.Release|x86.Build.0 = Release|x86
Wieso sind diese Configs jetzt weg?

2019-04-09 08:05 UTC, holzmaster commented on src/OpenPr0gramm/Http2CustomHandler.cs
> +            request.Version = new Version("2.0");
Ist davon auszugehen, dass der Server immer H2 kann? Was passiert, wenn er es nicht kann?

Setzt H2 nicht TLS voraus? Was ist, wenn der User kein TLS möchte, um schneller crawlen zu können? Bringt H2 überhaupt was bei simplen Rest-Aufrufen?

Version bitte static readonly machen.

2019-04-09 10:23 UTC, holzmaster commented
Danke für den PR! Habe ein paar Fragen dazu angemerkt.

2019-04-10 21:59 UTC, J-kit commented on OpenPr0gramm.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "OpenPr0gramm.Tests", "src\OpenPr0gramm.Tests\OpenPr0gramm.Tests.csproj", "{DD756BA6-655B-4106-955F-40079EC089D3}"
Keine ahnung :O 
Ist mir nicht aufgefallen ¯\_(ツ)_/¯
Wenn nötig kann ich das auch reverten

2019-04-10 22:02 UTC, J-kit commented on src/OpenPr0gramm/Http2CustomHandler.cs
> +            request.Version = new Version("2.0");
Nuja wenn der server kein h2 kann dann wird auf eine andere version geswitcht. 
Test:
`       using (var httpClient = new HttpClient(new Http2CustomHandler()))
            {
                // your custom code
                var result = await httpClient.GetAsync("http://itcorp.com");
                var resString= await result.Content.ReadAsStringAsync();
            }`

Bringt schon was, da die connections offen bleiben und nicht immer reconnected wird. Ausserdem könnte man dann mehrere requests gleichzeitig durch nur eine connection pressen. Das spart resourcen.

2019-04-10 22:07 UTC, holzmaster commented on src/OpenPr0gramm/Http2CustomHandler.cs
> +            request.Version = new Version("2.0");
Naja, being einem Rate-Limit von 1 Request pro Sekunde, wäre ich mir da nicht so sicher, ob man was bemerkt. HTTP1.1 hat auch Keep-Alive, was auch benutzt wird, AFAIK.

Solange er auf 1.1 umstellt, wenn man mein TLS möchte, ist das okay für mich. Sehe aber trotzdem nicht so ganz den Sinn. Wäre eher was dafür, wenn man Bilder runterlädt.

2019-04-10 22:08 UTC, merged